[package]
name = "vortex-sampling-compressor"
description = "Vortex compressor that uses statistical sampling"
version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
categories = { workspace = true }
readme = { workspace = true }

[dependencies]
arbitrary = { workspace = true, optional = true }
fsst-rs = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
vortex-alp = { workspace = true }
vortex-array = { workspace = true }
vortex-bytebool = { workspace = true }
vortex-datetime-dtype = { workspace = true }
vortex-datetime-parts = { workspace = true }
vortex-dict = { workspace = true }
vortex-dtype = { workspace = true }
vortex-error = { workspace = true }
vortex-fastlanes = { workspace = true }
vortex-fsst = { workspace = true }
vortex-roaring = { workspace = true }
vortex-runend = { workspace = true }
vortex-runend-bool = { workspace = true }
vortex-zigzag = { workspace = true }

[dev-dependencies]
chrono = { workspace = true }

[lints]
workspace = true

[features]
arbitrary = ["dep:arbitrary"]
