[package]
name = "vortex-datetime"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
vortex-array = { "path" = "../vortex-array" }
vortex-schema = { "path" = "../vortex-schema" }
linkme = { workspace = true }
log = { workspace = true }
