[package]
name = "vortex-ipc"
version = { workspace = true }
description = "Vortex IPC"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
arrow-buffer = { workspace = true }
flatbuffers = { workspace = true }
itertools = { workspace = true }
lending-iterator = "0.1.7"
nougat = "0.2.4"
streaming-iterator = "0.1.9"
vortex-array = { path = "../vortex-array" }
vortex-error = { path = "../vortex-error" }
vortex-flatbuffers = { path = "../vortex-flatbuffers" }
vortex-dtype = { path = "../vortex-dtype" }
vortex-scalar = { path = "../vortex-scalar" }

[build-dependencies]
flatc = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
simplelog = { workspace = true }
vortex-fastlanes = { path = "../vortex-fastlanes" }
vortex-alp = { path = "../vortex-alp" }
arrow = { workspace = true }
arrow-array = { workspace = true }
arrow-ipc = { workspace = true, features = ["lz4"] }
arrow-schema = { workspace = true }
arrow-select = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "ipc_take"
harness = false

[[bench]]
name = "ipc_array_reader_take"
harness = false