[package]
name = "vortex-runend"
version = { workspace = true }
description = "Vortex run end encoded array"
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
include = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
itertools = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
vortex-array = { path = "../../vortex-array" }
vortex-error = { path = "../../vortex-error" }
vortex-dtype = { path = "../../vortex-dtype" }
vortex-scalar = { path = "../../vortex-scalar" }

[lints]
workspace = true
